package cz.muni.airport.database;

/**
 * Autogenerated file for hibernate connection
 * @author rba on 15.10.2016.
 */
public class Main {
    public static void main(final String[] args) throws Exception {

    }
}