package cz.muni.airport.database;

import cz.muni.airport.model.Steward;
import cz.muni.airport.services.StewardService;
import java.util.List;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 * Autogenerated file for hibernate connection
 * @author rba on 15.10.2016.
 */
public class Main {
    public static void main(final String[] args) throws Exception {
        // create and configure beans
        ApplicationContext context =
            new ClassPathXmlApplicationContext("WEB-INF/applicationContext.xml");

        // retrieve configured instance
        StewardService stewardService =  context.getBean("stewardService", StewardService.class);

        Steward steward = new Steward();
        steward.setFirstName("Jano");
        steward.setLastName("Mrkva");

        stewardService.addSteward(steward);

		List<Steward> stewards = stewardService.getStewardByName("Jano", "Mrkva");
        for(Steward s : stewards) {
			System.out.println(s.toString());
        }
    }
}