package cz.muni.airport.database;

import cz.muni.airport.model.Airport;
import cz.muni.airport.model.Steward;
import cz.muni.airport.services.AirportService;
import cz.muni.airport.services.StewardService;
import java.util.List;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 * Autogenerated file for hibernate connection
 *
 * @author rba on 15.10.2016.
 */
public class Main {

    public static void main(final String[] args) throws Exception {
        // create and configure beans
        ApplicationContext context
                = new ClassPathXmlApplicationContext("WEB-INF/applicationContext.xml");

        // retrieve configured instance
        StewardService stewardService = context.getBean("stewardService", StewardService.class);

        Steward steward = new Steward();
        steward.setFirstName("Jano");
        steward.setLastName("Mrkva");

        stewardService.save(steward);

        // retrieve configured instance
        AirportService airport = (AirportService) context.getBean("airportService");

        Airport a = new Airport();
        a.setName("LVH");
        a.setCity("Brno");
        a.setCountry("CZ");

        airport.saveAirport(a);

        List<Airport> ports = airport.getAllAirports();
        for (Airport plane : ports) {
            System.out.println(plane.toString());
        }

    }
}
